### ISSUE TITLE
Dashboard TimeZone Issue on Showing Charts

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/dashboard#10]
There is still a timezone issue somewhere in how we show the monthly API calls stats. The backend does return the value correctly.

![](https://i.imgur.com/Zzj5TvB.png)

Shows up when browsing last week.

![](https://i.imgur.com/O5m2t4v.png)

**Comment by siddharthlatest** [comment]
@farhan687 On a second look, this happens consistently with Safari with all apps. So not a time zone issue.

App on safari:
![](https://i.imgur.com/y9p6ltr.png)

Same app on chrome:
![](https://i.imgur.com/We66Q6W.png)

**Comment by farhan687** [comment]
Fixed here 77fbb0e3b68f446712b1308aba515460d3409d96
