### ISSUE TITLE
UI/UX Enhancements

### ISSUE THREAD

**Issue by metagrover** [appbaseio/dashboard#103]
- [x] Add share icon in app-navbar for shared apps
- [x] Transform Back icon in app-navbar into a rounded-button
- [x] Fix Metrics stats limits in dashboard homepage
- [x] Better Error handling in Onboarding App creation - It renders a static error statement - We need to use server response to render the error message.

**Comment by jyash97** [comment]
Only metrics stats is remaining as it requires new API.

**Comment by jyash97** [comment]
This can be closed now as everything is completed
