### ISSUE TITLE
Dashboard resizing causes UI highlighting issues

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/dashboard#11]
![](https://i.imgur.com/ZnYMGJo.png)

- [x] Sidebar icons have styling issues
- [x] The footer has a weird overlay issue on the chart area. This also causes a problem on the mobile responsive view.

**Comment by farhan687** [comment]
Fixed here 6838f9f0df4fe79db5636cd40dcd24f5ca3cee06
