### ISSUE TITLE
Bug: Error modal's cancel button isn't responsive

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/dashboard#130]
Create a cluster with an invalid setting to see this error modal from here - https://dashboard.appbase.io/clusters/new.

![](https://i.imgur.com/8xMXbvF.png)

Easiest way to replicate is to change one of the request body values.

Solution: We should remove the `Cancel` button from here.

**Comment by metagrover** [comment]
We should replace all errors modals to use the error modal API:

```js
Modal.error({
    title: 'This is an error message',
    content: 'some messages...some messages...',
});
```
