### ISSUE TITLE
error in README.md

### ISSUE THREAD

**Issue by uptonking** [appbaseio/dashboard#19]
there is a compile error for  file `dashboard/app/shared/CopyToClipboard.js`
```
line 2
import Clipboard from 'Clipboard';
**should be**
import Clipboard from 'clipboard';
```

the default url should be [http://localhost:8000](http://localhost:8000), not 1357

**Comment by siddharthlatest** [comment]
@uptonking thanks for pointing both out. Have updated the port in webpack config to 1357. Let us know if you see any other compile error(s).
