### ISSUE TITLE
Deleting an app from a filtered view opens up tutorial

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/dashboard#23]
### Steps to reproduce:

1. Create a filtered view with a single app
2. Delete the app
// Watch the tutorial start.

The logic we have for starting the tutorial is flawed, we should check for all user apps v/s what is in the current view.

**Comment by farhan687** [comment]
Fixed here: 99471bb24c9b3e4fbe5024b163e3617b4eed351e
