### ISSUE TITLE
UI for transferring app owernship

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/dashboard#24]
- [x] App ownership can be transferred from `https://dashboard.appbase.io/<appname>/team` page. Add a "Transfer Ownership" button which takes in an e-mail field to transfer the app's ownership to.

- [x] Ownership transfer requires a confirmation dialog where the user needs to enter the &lt;appname> before being able to transfer the ownership.

The endpoint for doing this is `POST /app/:appid/changeowner`. It expects a JSON object with key `owner` and value as the e-mail id to whom the app's ownership should be transferred to.

**Comment by farhan687** [comment]
Implemented here: 9b748dad081b9bf57ad0766c367d63f34db69840
