### ISSUE TITLE
Improve UI/UX

### ISSUE THREAD

**Issue by divyanshu013** [appbaseio/dashboard#42]
- [x] Use https in dejavu for links from dashboard to allow importer script to load correctly
- [x] Check for elements which are getting blocked
- [ ] Transferring ownership to a user who doesn't exist should show an appropriate message
- [ ] Support importing data and adding data via GUI when creating app
- [ ] Show appropriate message for mobile "Optimized for desktop use"

**Comment by siddharthlatest** [comment]
- [ ] When creating an app, the "Create App" button's pressed state has an incoherent style.
- [ ] When a user isn't logged in, clicking on top left navbar's `appbase.io` logo should redirect to the home page (currently it redirects to the signin page).

**Comment by metagrover** [comment]
v2 addresses all these issues.
