### ISSUE TITLE
Preserve apps order in the manager view

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/dashboard#5]
To minimize the re-ordering disruption when making a network request for fetching all the apps, we can preserve apps order in the manager view.

**Comment by farhan687** [comment]
Fixed here: f3f0faff96c3810bae4c2331f36a828993813960 and now we are preserving last sortby option as well 42e59106117f2c1c3956059d723fe092c5f1f6c8

**Comment by siddharthlatest** [comment]
@farhan687 there are still some remaining issues here.

- [ ] Try creating a new app, it won't show up in the sorted order. Even when I refresh the browser view, it shows up as an out of place.
- [ ] Sort by app name functionality works differently, i.e. it doesn't treat shared apps separately from owned apps.

**Comment by farhan687** [comment]
Fixed here 04b2a921a6fc5f3d9863feefd03fcd7d95361ea2
