### ISSUE TITLE
Bug: Mapping failure crashes the entire dashboard

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/dashboard#50]
A failure in parsing a mapping property (which is also a potential bug) is causing the entire dashboard to not render.

![](https://i.imgur.com/LFreUfS.png)

We should allow the user to navigate to other views even when there's a parse error or a network related error.

**Comment by metagrover** [comment]
#98 should fix this.

**Comment by jyash97** [comment]
This can be closed now as #98 is merged
