### ISSUE TITLE
Feature: Help support design

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/dashboard#64]
We will show a help icon which will open up the following options for the users:

1. Ask us anything! 👋 
```
<!--[if lte IE 8]>
<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2-legacy.js"></script>
<![endif]-->
<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2.js"></script>
<script>
  hbspt.forms.create({
	portalId: "4709730",
	formId: "e2465ba7-75c6-4e40-b4be-0c8dfe553bbb"
});
</script>
```

2. Get Support! https://appbase.io/pricing/#support

3. New Updates <some blog post or some other href>

Link to Terms & Privacy.

Design Reference:

![](https://i.imgur.com/nRKNhAR.png)

@jyash97

**Comment by jyash97** [comment]
This can be closed now. Merged in #69
